### ISSUE TITLE
Bone weights not functioning in Skinned FLVER0 model

### ISSUE THREAD

**Issue by thegreatgramcracker** [Grimrukh/soulstruct-blender#79]
Problem:
I have a custom mesh to replace the maiden in black model in Demon's Souls. I have ensured the vertices are rigged to the exact same skeleton used by the vanilla model, and there are vertex weights clearly painted on the model. I went through every field I could find to make sure it was set up like how Soulstruct expects, but it seems like on export, the boneweights are non-existent (analyzing it with soulsformats shows they are all set to {1,0,0,0}. There are no errors on export and it even imports just fine from the exported flver with the boneweights still visible in blender, so I have no idea what could be wrong. This is how it looks in game: 
![BLUS30443_screenshot_2024_10_06_12_43_27](https://github.com/user-attachments/assets/d3cc43e5-b2ed-434e-b06e-d797c252589e)

This is the view in blender:
![image](https://github.com/user-attachments/assets/07ae6708-1fcd-439c-ab09-5a7ff5d4dfe3)

My workflow for adding it to the game has been: 

1. Export as loose flver with DES compression
2. bring it in to the c7150 chrbnd folder
3. remove dcx with witchy
4. repack the chrbnd

**Comment by Grimrukh** [comment]
I'll investigate this; I'm 95% sure it's because the FLVER is being mistaken for an unrigged Map Piece... in the FLVER properties, is Bone Data Type set to `Edit Bones`?

Also, if you use the "Export Character" operator, this should ensure this doesn't happen. (That operator is now fixed as per the other bug!)

Let me know if that doesn't solve the issue and I'll dig into this more. I plan to tidy up the whole Map Piece vs. other FLVER bone treatment eventually...

**Comment by thegreatgramcracker** [comment]
Hi, thanks for looking in to it. I am still receiving a crash if I export as a character, but it is now exporting in to the correct binder at least (but it doesn't seem like it exported the textures into the tpf). I noticed that exporting once into the vanilla chrbnd gives no errors, but crashes on load. If I try to export again, I get this error:
```
Python: Traceback (most recent call last):
  File "C:\Users\thegr\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\io_soulstruct\flver\models\export_operators.py", line 437, in execute
    model_stem, chrbnd, flver, textures = self.get_binder_and_flver(
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\thegr\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\io_soulstruct\flver\models\export_operators.py", line 365, in get_binder_and_flver
    binder = binder_class.from_path(binder_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\thegr\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\io_soulstruct_lib\soulstruct\containers\core.py", line 379, in from_path
    binder = cls.from_bytes(reader, bdt_reader)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\thegr\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\io_soulstruct_lib\soulstruct\containers\core.py", line 307, in from_bytes
    instance = cls.from_reader(reader)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\thegr\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\io_soulstruct_lib\soulstruct\containers\core.py", line 419, in from_reader
    return cls(entries=entries, is_split_bxf=bdt_reader is not None, **header_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 16, in __init__
  File "C:\Users\thegr\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\io_soulstruct_lib\soulstruct\containers\binder_types.py", line 45, in __post_init__
    self.flvers[entry.minimal_stem] = entry.to_binary_file(self.FLVER_CLASS)
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\thegr\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\io_soulstruct_lib\soulstruct\containers\entry.py", line 202, in to_binary_file
    binary_file = binary_file_cls.from_bytes(self.get_uncompressed_data())
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\thegr\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\io_soulstruct_lib\soulstruct\base\base_binary_file.py", line 140, in from_bytes
    binary_file = cls.from_reader(reader)
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\thegr\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\io_soulstruct_lib\soulstruct\base\models\flver0\core.py", line 79, in from_reader
    byte_order = ByteOrder.from_reader_peek(reader, 2, 6, b"B\0", b"L\0")
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\thegr\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\io_soulstruct_lib\constrata\byte_order.py", line 38, in from_reader_peek
    raise ValueError(f"Could not determine byte order from bytes: {peeked}")
ValueError: Could not determine byte order from bytes: b'\xfd\x89'
```

Also, trying to import the first export gives me a similar (but slightly smaller) error:

```
Python: Traceback (most recent call last):
  File "C:\Users\thegr\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\io_soulstruct_lib\soulstruct\base\base_binary_file.py", line 140, in from_bytes
    binary_file = cls.from_reader(reader)
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\thegr\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\io_soulstruct_lib\soulstruct\base\models\flver0\core.py", line 79, in from_reader
    byte_order = ByteOrder.from_reader_peek(reader, 2, 6, b"B\0", b"L\0")
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\thegr\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\io_soulstruct_lib\constrata\byte_order.py", line 38, in from_reader_peek
    raise ValueError(f"Could not determine byte order from bytes: {peeked}")
ValueError: Could not determine byte order from bytes: b'\xfd\x89'
```
I've attached the file that got exported.

[c7150.chrbnd.dcx.zip](https://github.com/user-attachments/files/17367141/c7150.chrbnd.dcx.zip)

Thanks!

**Comment by Grimrukh** [comment]
I've fixed the CHRBND reading issues (DeS DCX decompression bug) and now working on the vertex weight issue. I suspect that the vertex data layout for the material isn't being generated properly, which is why SS can read it again but the game won't.

**Comment by Grimrukh** [comment]
I've taken a look at your files and so far, the only thing I've noticed is that your new model has bone weights that don't always add up to 1.0? In both Soulstruct and SoulsFormats, I see vertices 0-135 are all weighted to local bone 3 or 4 only, but vertex 136 has 1.0 weights to both local bone 0 and 14. Does that sound right? When you say SoulsFormats sees all weights as being (1, 0, 0, 0), do you mean literally all of them?

**Comment by thegreatgramcracker** [comment]
I'll try again with the new version tonight and let you know how it goes, I'll also double check my bone weight data since I might have got it wrong (I just used console print statements and soulsformats to check). There could also be user error or something wrong with the model on my part since I didn't create it, it came from a friend who I commissioned. Although it did used to work when I converted it into a ds1 model with fbx2flver and then used Dropoff's tool to convert DS1 to DeS, but that was using the SoulsModelTool export as a base instead of Soulstruct.

**Comment by thegreatgramcracker** [comment]
Hi, I tried on the new version and am still receiving crash on load issues, however, I think it's related to the tpf file. I unpacked with Witchy, replaced the tpf with my previous working one, then repacked, and the model was able to load. Despite this, it still looked all messed up like before. I tested normalizing all the bone weights and now they look good when I read through them with Soulsformats, but model in game still looks messed up. I attached a screenshot and also the chrbnd of what happens if I just click "Export character" over top of the vanilla chrbnd.
![BLUS30443_screenshot_2024_10_15_18_15_34](https://github.com/user-attachments/assets/108cadb2-4d1c-4842-9129-813df31e417b)

[c7150.chrbnd.dcx.zip](https://github.com/user-attachments/files/17387581/c7150.chrbnd.dcx.zip)

**Comment by thegreatgramcracker** [comment]
If it is tpf files, I have some information that might be able to help. I noticed that TKGP's Soulsformats can't actually write ps3 tpfs properly, so Natsu had to help me with a slight modification to it.

This is a snippet of the original tpf Write() method:
```
long dataStart = bw.Position;
for (int i = 0; i < Textures.Count; i++)
{
    // Padding for texture data varies wildly across games,
    // so don't worry about this too much
    if (Textures[i].Bytes.Length > 0)
        bw.Pad(4);

    Textures[i].WriteData(bw, i);
}
bw.FillInt32("DataSize", (int)(bw.Position - dataStart));
```
This was the modification:
```
int dataSize = 0;
for (int i = 0; i < Textures.Count; i++)
{
    if (Textures[i].Bytes.Length > 0)
        bw.Pad(0x80);

    long textureStart = bw.Position;
    Textures[i].WriteData(bw, i);
    long textureEnd = bw.Position;
    dataSize += (int)(textureEnd - textureStart);
}
bw.Pad(0x80);
bw.FillInt32("DataSize", dataSize);
```

However, a better thing to look at might be [SoulsFormatsNEXT](https://github.com/soulsmods/SoulsFormatsNEXT/tree/master), since it seems to write them fine out of the box (also with Natsu's fix, the file size always was identical even if the textures were smaller. With SoulsFormatsNEXT, the files sizes were shrunk as they should be when I lowered the colors of the textures).

Another piece of info I can give is something you probably already are aware of, but the actual textures portion of ps3 tpfs do not contain the bytes for a full dds file. They all have their headers stripped out and just have their pixel data left over. But the header info is actually in a different part of the tpf file (I think it still precedes each texture, not sure exactly). So if you are trying to look at them the same as PC textures and just putting the whole dds file bytes in the texture portion, it will be messed up because in that same spot on PS3 its just pixels.

**Comment by thegreatgramcracker** [comment]
Oh, also I noticed a difference in bone rotations. This was just with comparing the vanilla flver with a simple import and export in blender of the vanilla chrbnd (no modifications).

![image](https://github.com/user-attachments/assets/4d83cd1e-6793-4d5b-83a8-eb9a081f62e7)

**Comment by thegreatgramcracker** [comment]
Update number 5 (sorry)
I just copied the bytes from the vanilla flver's skeleton into the exported one, and set "Dynamic" and "Unk03" bytes on each mesh to 1, since that's how it was set in the original flver but oddly not the export. This was the result, no animation and she's colored black because I was fiddling with vertex colors, but still at least it looks mostly right!
![BLUS30443_screenshot_2024_10_15_22_11_08](https://github.com/user-attachments/assets/7cbd6ec7-681f-4225-9489-29da6c93925e)

**Comment by Grimrukh** [comment]
This should now be fixed in v2.1.8. Combination of problems:

TPF files were being read and re-written by Soulstruct even when not actually exported from Blender, and there was corruption going on - I've fixed the TPF read/write for PS3, but also they don't get read/written pointlessly now anyway.

Also fixed the 'Dynamic' field (renamed 'Is Bind Pose' since it's clearly the same as that in FLVER2) for rigged models. 

The 'Unk03' value you were manually re-enabling is 'Is Triangle Strip', which should indeed be disabled for Blender exports (I can't export triangle strips and DeS thankfully is fine with that).
